# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VK1tBwR9rIanEvmUdt5Qs5nqabj7HjCP
"""

Table product_categories {
  category_id int [pk]
  category_name varchar
}

Table suppliers {
  supplier_id int [pk]
  supplier_name varchar
  contact_info text
}

Table products {
  product_id int [pk]
  product_name varchar
  price decimal
  category_id int [ref: > product_categories.category_id]
  supplier_id int [ref: > suppliers.supplier_id]
}

Table customers {
  customer_id int [pk]
  customer_name varchar
  phone varchar
  email varchar
  address text
}

Table employees {
  employee_id int [pk]
  employee_name varchar
  position varchar
  hire_date date
}

Table promotions {
  promotion_id int [pk]
  promotion_name varchar
  discount_percent decimal
  start_date date
  end_date date
}

Table orders {
  order_id int [pk]
  customer_id int [ref: > customers.customer_id]
  employee_id int [ref: > employees.employee_id]
  promotion_id int [ref: > promotions.promotion_id]
  order_date datetime
}

Table order_items {
  order_item_id int [pk]
  order_id int [ref: > orders.order_id]
  product_id int [ref: > products.product_id]
  quantity int
  price_at_purchase decimal
}